# Generated by Django 3.2.6 on 2021-09-07 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMyProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfProduct', models.CharField(max_length=255)),
                ('NameOfMyProduct', models.CharField(blank=True, max_length=255)),
                ('productMyUrl', models.CharField(blank=True, max_length=255)),
                ('productSkroutzUrl', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorAnalysisModel_retry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorList',
            fields=[
                ('CompetitorID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('CompetitorName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataMainTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('my_price', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('my_productName', models.CharField(max_length=255)),
                ('my_availability', models.CharField(max_length=255)),
                ('company', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('bestPriceAvailability', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DataMainTable_allData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('my_price', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('my_productName', models.CharField(max_length=255)),
                ('my_availability', models.CharField(max_length=255)),
                ('company', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('bestPriceAvailability', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.allmyproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
                'index_together': {('user', 'product')},
            },
        ),
    ]
