# Generated by Django 3.2.6 on 2021-12-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
